### ISSUE TITLE
[Feature]: 설문 페이지 구현

### ISSUE THREAD

**Issue by jknadan** [sharebookshelf/Gongcheck-FE#2]
### Description
- 이미지 업로드 후 분석 중, 사용자에게 간단한 설문을 입력받는 페이지를 구현한다.
- branch이름 : feat/survey

### TODO
- [x] 설문 페이지 디렉토리(route) 생성 
- [ ] page.tsx 설계
- [ ] 설문 제출 후 Back-End 서버로 결과값 전달

### ETC (관련 자료 및 링크, 사진 등)

![image](https://github.com/sharebookshelf/Gongcheck-FE/assets/66247589/90ffa0e0-70ae-4356-900d-4c973ddae69e)
