### ISSUE TITLE
[Feature] 이미지 업로드 및 사용자 정보 입력 화면

### ISSUE THREAD

**Issue by speardragon** [sharebookshelf/Gongcheck-FE#3]
### Description
- 분석할 책장 이미지와 간단한 사용자 정보를 입력받는 화면을 구현한다.
- branch 명: feat/onboard

### TODO
- [x] 이미지 업로드 컴포넌트
- [x] 사용자 정보 입력폼 컴포넌트
- [x] 입력폼 전송 버튼
 - [x] 서버로 위의 데이터들 보내기

### ETC (관련 자료 및 링크, 사진 등)
<img width="438" alt="스크린샷 2024-02-08 오후 5 34 23" src="https://github.com/sharebookshelf/Gongcheck-FE/assets/79521972/4bfa9ec2-5f74-4c46-a9fb-3a8846115f78">

**Comment by jknadan** [comment]
👍🏻

**Comment by jknadan** [comment]
👍🏻
